package appfarm.model

import _root_.net.liftweb.mapper._
import _root_.net.liftweb.util._
import _root_.net.liftweb.common._

/**
 * The singleton that has methods for accessing the database
 */
object File extends File with KeyedMetaMapper[String, File] {
  override def dbTableName = "files" // define the DB table name
}

class File extends KeyedMapper[String, File] {
  def getSingleton = File // what's the "meta" server

  def primaryKeyField = name

  object name extends MappedStringIndex(this, 96) {
    override def writePermission_? = true
    override def dbAutogenerated_? = false
    override def dbNotNull_? = true
    override def dbIndexed_? = true
  }

  object content extends MappedBinary(this) {
    override def writePermission_? = true
  }

}
